# Generated by Django 4.2.24 on 2025-10-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.IntegerField(choices=[(0, 'MAIN MENU'), (1, 'KIDS'), (2, 'SUNDAY'), (3, 'BEERS & CIDERS'), (4, 'WINES'), (5, 'OTHER DRINKS')])),
                ('sub_menu_title', models.IntegerField(choices=[(0, 'STARTERS'), (1, 'MAINS'), (2, 'STEAKS'), (3, 'PIES'), (4, 'BURGERS'), (5, 'SIDES'), (6, 'DESSERTS'), (7, 'VEGGIES'), (8, 'ICE CREAM'), (9, 'DRINKS'), (10, 'PICK & MIX'), (11, 'ROASTS'), (12, 'KIDS ROASTS'), (13, 'BEER'), (14, 'CIDER'), (15, 'WINES'), (16, 'WHITE'), (17, 'RED'), (18, 'SPARKLING'), (19, 'SOFT DRINKS')])),
                ('item_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
