# Generated by Django 4.2.24 on 2025-09-26 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookATable',
            fields=[
                ('book_table_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('booking_time', models.IntegerField(choices=[('0', '12:00 PM'), ('1', '12:15 PM'), ('2', '12:30 PM'), ('3', '12:45 PM'), ('4', '1:00 PM'), ('5', '1:15 PM'), ('6', '1:30 PM'), ('7', '1:45 PM'), ('8', '2:00 PM'), ('9', '2:15 PM'), ('10', '2:30 PM'), ('11', '2:45 PM'), ('12', '3:00 PM'), ('13', '3:15 PM'), ('14', '3:30 PM'), ('15', '3:45 PM'), ('16', '4:00 PM'), ('17', '4:15 PM'), ('18', '4:30 PM'), ('19', '4:45 PM'), ('20', '5:00 PM'), ('21', '5:15 PM'), ('22', '5:30 PM'), ('23', '5:45 PM'), ('24', '6:00 PM'), ('25', '6.15 PM'), ('26', '6:30 PM'), ('27', '6:45 PM'), ('28', '7:00 PM'), ('29', '7:15 PM'), ('30', '7:30 PM'), ('31', '7:45 PM'), ('32', '8:00 PM'), ('33', '8:15 PM'), ('34', '8:30 PM'), ('35', '8:45 PM'), ('36', '9:00 PM')], default='0')),
                ('number_of_guests', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('booking_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('occasion', models.IntegerField(choices=[('0', 'None'), ('1', 'Birthday'), ('2', 'Anniversary'), ('3', 'business_meal'), ('4', 'family_meal'), ('5', 'date_night'), ('6', 'Other')], default='0')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('book_a_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_booking', to='book_a_table.bookatable')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
