# Generated by Django 4.2.24 on 2025-10-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_a_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookatable',
            options={'ordering': ['-created_on']},
        ),
    ]
