# Generated by Django 4.2.24 on 2025-10-13 21:16

import book_a_table.models
import datetime
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('book_a_table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookatable',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='bookatable',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='bookatable',
            name='approved',
            field=models.IntegerField(choices=[(0, 'Awaiting Booking Confirmation'), (1, 'Booking Confirmed')], default=0),
        ),
        migrations.AddField(
            model_name='bookatable',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookatable',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 13, 21, 4, 5, 550056, tzinfo=datetime.timezone.utc), validators=[book_a_table.models.BookATable.validate_date]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookatable',
            name='email',
            field=models.EmailField(default=datetime.datetime(2025, 10, 13, 21, 15, 8, 406965, tzinfo=datetime.timezone.utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookatable',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2025, 10, 13, 21, 15, 34, 903183, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookatable',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2025, 10, 13, 21, 15, 49, 752216, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookatable',
            name='occasion',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Birthday'), (2, 'Anniversary'), (3, 'Business Meal'), (4, 'Family Meal'), (5, 'Date Night'), (6, 'Other')], default=0),
        ),
        migrations.AddField(
            model_name='bookatable',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default=datetime.datetime(2025, 10, 13, 21, 16, 16, 967063, tzinfo=datetime.timezone.utc), max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookatable',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookatable',
            name='time',
            field=models.IntegerField(choices=[(0, '12:00 PM'), (1, '12:15 PM'), (2, '12:30 PM'), (3, '12:45 PM'), (4, '1:00 PM'), (5, '1:15 PM'), (6, '1:30 PM'), (7, '1:45 PM'), (8, '2:00 PM'), (9, '2:15 PM'), (10, '2:30 PM'), (11, '2:45 PM'), (12, '3:00 PM'), (13, '3:15 PM'), (14, '3:30 PM'), (15, '3:45 PM'), (16, '4:00 PM'), (17, '4:15 PM'), (18, '4:30 PM'), (19, '4:45 PM'), (20, '5:00 PM'), (21, '5:15 PM'), (22, '5:30 PM'), (23, '5:45 PM'), (24, '6:00 PM'), (25, '6:15 PM'), (26, '6:30 PM'), (27, '6:45 PM'), (28, '7:00 PM'), (29, '7:15 PM'), (30, '7:30 PM'), (31, '7:45 PM'), (32, '8:00 PM'), (33, '8:15 PM'), (34, '8:30 PM'), (35, '8:45 PM'), (36, '9:00 PM')], default=0),
        ),
        migrations.AddField(
            model_name='bookatable',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='BookingDetails',
        ),
    ]
