# Generated by Django 4.2.24 on 2026-01-19 14:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('book_a_table', '0002_alter_bookatable_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookatable',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+441234567890', max_length=13, null=True, region=None, unique=True),
        ),
    ]
